apiVersion: batch/v1
kind: Job
metadata:
  name: amanuensisdb-create
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: eks.amazonaws.com/capacityType
                operator: In
                values:
                - ONDEMAND 
      automountServiceAccountToken: false
      volumes:
        - name: creds-volume
          secret:
            secretName: "amanuensis-creds"
      containers:
      - name: amanuensis
        GEN3_AMANUENSIS_IMAGE
        imagePullPolicy: Always
        env:
          - name: PYTHONPATH
            value: /var/www/amanuensis
        volumeMounts:
          - name: "creds-volume"
            readOnly: true
            mountPath: "/var/www/amanuensis/creds.json"
            subPath: creds.json
        command: ["/bin/bash" ]
        args:
          - "-c"
          # Script always succeeds if it runs (echo exits with 0)
          - |
            eval $(python 2> /dev/null <<EOM
            import json

            creds = json.load(open('/var/www/amanuensis/creds.json', 'r'))
            print('declare -A db_creds')
            for key in ['db_host', 'db_username', 'db_password', 'db_database']:
              print("db_creds['%s']='%s'" % (key, creds[key]))
            EOM
            )
            userportaldatamodel-init --username "${db_creds[db_username]}" --password "${db_creds[db_password]}" --host "${db_creds[db_host]}" --db "${db_creds[db_database]}"
            echo "Exit code: $?"
      restartPolicy: Never
