kind: Service
apiVersion: v1
metadata:
  name: gearbox-service
spec:
  selector:
    app: gearbox
    release: production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
      name: http
  type: ClusterIP

