# Ops team so far
# diw  emalinowski  fauzi  jmazzone  phillis  rarya  rarya.old  reubenonrye  rpowell1  seapasulli  zflamig
- hosts: "{{ _hosts }}"
  tasks:
  - authorized_key:
      user: "{{ _user }}"
      state: present
      manage_dir: true
      key: '{{ lookup(''file'', item) }}'
    loop:
       - ../keys/fauzi
       - ../keys/diw
       - ../keys/emalinowski
       - ../keys/jmazzone
       - ../keys/rpowell1
       - ../keys/seapasulli
       - ../keys/rarya
       - ../keys/zflamig
       - ../keys/phillis
       - ../keys/reubenonrye
